---
abstract: 'A script to test the tone perception of your ears.'
author:
  - 'W. Luis Mochan <mochan@fis.unam.mx>'
build_requires:
  Pod::Coverage::TrustPod: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4218, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-tonematch
provides:
  App::tonematch:
    file: lib/App/tonematch.pm
    version: '0.002'
requires:
  Tk: '0'
  Tk::MTDial: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '0.002'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
